### ISSUE TITLE
HTML version of the tutorial on the website is not up-to-date

### ISSUE THREAD

**Issue by Zimmi48** [coq/www#52]
The tutorial available here https://coq.inria.fr/tutorial/ has not been updated with the latest version at the time of the 8.7.0 release.

How come that the script uploading the reference manual and the standard library did not also upload the tutorial? Did it use to be uploaded manually?

**Comment by letouzey** [comment]
For the moment, the tutorial is considered to be a part of the static pages of the site (see the `pages/tutorial` directory in this git repository), while the online refman and stdlib docs are rather considered to be part of the `/distrib` part of the site, hence updated at each release (through the `distrib/current/` symlink). This classification dates back to my move from drupal to static html pages (and migth actually be even older than that).

Anyway, with the current frenzy about compatibility, how could this current tutorial be broken ?

Ok, that was a joke, the sad truth is probably that everything in this tutorial would deserve a update
by some brave volunteer(s). See `doc/tutorial/Tutorial.tex` in the Coq archive for the initial sources of this tutorial, but beware that I (or others) probably edited the `pages/tutorial/*.html` files here directly during the move to static pages (or since), so check the history of these pages as well.

Best
Pierre

**Comment by Zimmi48** [comment]
In fact this update was already done by me see coq/coq#842. That's why I'm particularly interested in uploading an up-to-date version. But thanks for the info. I should be able to update it myself then.
